development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c6cf6d4f5dcaa72a6da2f0f8659e8af8@spinyfin.redistogo.com:9636/
  channel_prefix: sparring_meetup_production
